### PR TITLE
Update icon to play well with dark backgrounds

### PR DESCRIPTION
**Pull request by Pustur**
The current icon of this extension is not very visible in dark themes, so I tried to fix it by adding a light grey border around.

What do you say?

Before:
before

After:
after

I'll leave the `psd` file here as well in case anyone needs it: 
[logo.psd.zip](https://github.com/earshinov/vscode-permute-lines/files/3543712/logo.psd.zip)

### CODE REVIEW

**Comment by earshinov** [comment]
@Pustur , Please take my apologies for a late response. Thank you for taking your time for updating the icon and making this MR. I will review the icon in the coming days and apply the same changes to icons of my other extensions.

Out of curiosity, how did you replace the icon in the VS Code interface shown in the screenshot?

**Comment by Pustur** [comment]
Hey, don't worry you can take your time 🙂
Thanks for considering this PR.

> Out of curiosity, how did you replace the icon in the VS Code interface shown in the screenshot?

By opening the developer tools and replacing the image `src` with my own. To simplify I [base64 encode](https://www.base64-image.de) my images first so that they are loaded directly inline and I don't have to worry about paths.

**Comment by earshinov** [comment]
@Pustur , what do you think of this version?

image

I changed outline width to 1px and color from plain white #fff to #ccc, the color VS Code applies to text. In my opinion, with this icon the extension page within VS Code look more visually balanced. In the sidebar your original icon looks better, but you can't have it all...

PNG and PSD files: [logo.zip](https://github.com/earshinov/vscode-permute-lines/files/3561165/logo.zip)
(_Note: I only have a prehistoric version of Photoshop, so there may be compatibility issues_)

_Update_: Actually 1px **white** outline is even better. I love how it looks. In contrast to #ccc, it does not look dirty on white background. And on black background 1px white outline looks like it is gray!

**Comment by Pustur** [comment]
@earshinov Yeah that looks good to me, maybe I went a little overboard with the border thickness 😄

Maybe a shadow or a glow could also work in this case, but I'll let you decide, it's your extension after all!

**Comment by earshinov** [comment]
I have published a new version with an updated icon. Also I applied similar modifications to icons of my other VS Code extensions. Thanks!

**Pull request closed without merging**
